//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizzCraftClient.TeacherServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Teacher", Namespace="http://schemas.datacontract.org/2004/07/QuizzCraftService.Models")]
    [System.SerializableAttribute()]
    public partial class Teacher : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreatedQuizzesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeacherIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatedQuizzes {
            get {
                return this.CreatedQuizzesField;
            }
            set {
                if ((this.CreatedQuizzesField.Equals(value) != true)) {
                    this.CreatedQuizzesField = value;
                    this.RaisePropertyChanged("CreatedQuizzes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeacherId {
            get {
                return this.TeacherIdField;
            }
            set {
                if ((this.TeacherIdField.Equals(value) != true)) {
                    this.TeacherIdField = value;
                    this.RaisePropertyChanged("TeacherId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TeacherServiceReference.ITeacherService")]
    public interface ITeacherService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/AddTeacher", ReplyAction="http://tempuri.org/ITeacherService/AddTeacherResponse")]
        string AddTeacher(QuizzCraftClient.TeacherServiceReference.Teacher teacher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/AddTeacher", ReplyAction="http://tempuri.org/ITeacherService/AddTeacherResponse")]
        System.Threading.Tasks.Task<string> AddTeacherAsync(QuizzCraftClient.TeacherServiceReference.Teacher teacher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/GetTeacherByEmail", ReplyAction="http://tempuri.org/ITeacherService/GetTeacherByEmailResponse")]
        QuizzCraftClient.TeacherServiceReference.Teacher GetTeacherByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/GetTeacherByEmail", ReplyAction="http://tempuri.org/ITeacherService/GetTeacherByEmailResponse")]
        System.Threading.Tasks.Task<QuizzCraftClient.TeacherServiceReference.Teacher> GetTeacherByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/GetTeacherById", ReplyAction="http://tempuri.org/ITeacherService/GetTeacherByIdResponse")]
        QuizzCraftClient.TeacherServiceReference.Teacher GetTeacherById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/GetTeacherById", ReplyAction="http://tempuri.org/ITeacherService/GetTeacherByIdResponse")]
        System.Threading.Tasks.Task<QuizzCraftClient.TeacherServiceReference.Teacher> GetTeacherByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/VerifyTeacher", ReplyAction="http://tempuri.org/ITeacherService/VerifyTeacherResponse")]
        QuizzCraftClient.TeacherServiceReference.Teacher VerifyTeacher(string email, string epassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/VerifyTeacher", ReplyAction="http://tempuri.org/ITeacherService/VerifyTeacherResponse")]
        System.Threading.Tasks.Task<QuizzCraftClient.TeacherServiceReference.Teacher> VerifyTeacherAsync(string email, string epassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITeacherServiceChannel : QuizzCraftClient.TeacherServiceReference.ITeacherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TeacherServiceClient : System.ServiceModel.ClientBase<QuizzCraftClient.TeacherServiceReference.ITeacherService>, QuizzCraftClient.TeacherServiceReference.ITeacherService {
        
        public TeacherServiceClient() {
        }
        
        public TeacherServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TeacherServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeacherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeacherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddTeacher(QuizzCraftClient.TeacherServiceReference.Teacher teacher) {
            return base.Channel.AddTeacher(teacher);
        }
        
        public System.Threading.Tasks.Task<string> AddTeacherAsync(QuizzCraftClient.TeacherServiceReference.Teacher teacher) {
            return base.Channel.AddTeacherAsync(teacher);
        }
        
        public QuizzCraftClient.TeacherServiceReference.Teacher GetTeacherByEmail(string email) {
            return base.Channel.GetTeacherByEmail(email);
        }
        
        public System.Threading.Tasks.Task<QuizzCraftClient.TeacherServiceReference.Teacher> GetTeacherByEmailAsync(string email) {
            return base.Channel.GetTeacherByEmailAsync(email);
        }
        
        public QuizzCraftClient.TeacherServiceReference.Teacher GetTeacherById(int id) {
            return base.Channel.GetTeacherById(id);
        }
        
        public System.Threading.Tasks.Task<QuizzCraftClient.TeacherServiceReference.Teacher> GetTeacherByIdAsync(int id) {
            return base.Channel.GetTeacherByIdAsync(id);
        }
        
        public QuizzCraftClient.TeacherServiceReference.Teacher VerifyTeacher(string email, string epassword) {
            return base.Channel.VerifyTeacher(email, epassword);
        }
        
        public System.Threading.Tasks.Task<QuizzCraftClient.TeacherServiceReference.Teacher> VerifyTeacherAsync(string email, string epassword) {
            return base.Channel.VerifyTeacherAsync(email, epassword);
        }
    }
}
